"""News table

Revision ID: 91b1d6f2be30
Revises: f59c9bb04f1a
Create Date: 2024-01-17 19:38:00.070737

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91b1d6f2be30'
down_revision = 'f59c9bb04f1a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('news', schema=None) as batch_op:
        batch_op.add_column(sa.Column('url', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('cover', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('photos', sa.String(length=2000), nullable=True))
        batch_op.add_column(sa.Column('photographers', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('date', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('date_created', sa.DateTime(), nullable=False))
        batch_op.create_unique_constraint('unique_url_constraint', ['url'])
        batch_op.drop_column('date_posted')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('date_created',
               existing_type=sa.DATETIME(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('date_created',
               existing_type=sa.DATETIME(),
               nullable=True)

    with op.batch_alter_table('news', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_posted', sa.DATETIME(), nullable=True))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('date_created')
        batch_op.drop_column('date')
        batch_op.drop_column('photographers')
        batch_op.drop_column('photos')
        batch_op.drop_column('cover')
        batch_op.drop_column('url')

    # ### end Alembic commands ###
