"""News table URL update

Revision ID: 9250b3480e35
Revises: 91b1d6f2be30
Create Date: 2024-01-17 19:54:30.644808

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9250b3480e35'
down_revision = '91b1d6f2be30'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('news', schema=None) as batch_op:
        batch_op.add_column(sa.Column('news_url', sa.String(length=255), nullable=False))
        batch_op.drop_constraint('unique_url_constraint', type_='unique')
        batch_op.create_unique_constraint('uq_news_url', ['news_url'])
        batch_op.drop_column('url')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('news', schema=None) as batch_op:
        batch_op.add_column(sa.Column('url', sa.VARCHAR(length=255), nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_unique_constraint('uq_news_url', ['url'])
        batch_op.drop_column('news_url')

    # ### end Alembic commands ###
