"""news url in pt and en

Revision ID: e17d1868b604
Revises: 3b7ca4f88be1
Create Date: 2024-02-14 10:57:00.909861

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e17d1868b604'
down_revision = '3b7ca4f88be1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('news', schema=None) as batch_op:
        batch_op.add_column(sa.Column('news_url_en', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('news_url_pt', sa.String(length=255), nullable=False))
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=20),
               nullable=True)
        batch_op.drop_constraint('uq_news_url', type_='unique')
        batch_op.create_unique_constraint('news_url_pt', ['news_url_pt'])
        batch_op.create_unique_constraint('news_url_en', ['news_url_en'])
        batch_op.drop_column('news_url')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('news', schema=None) as batch_op:
        batch_op.add_column(sa.Column('news_url', sa.VARCHAR(length=255), nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_unique_constraint('uq_news_url', ['news_url'])
        batch_op.alter_column('status',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.drop_column('news_url_pt')
        batch_op.drop_column('news_url_en')

    # ### end Alembic commands ###
